package by.htp.sportequip.file;

public enum TagName {
	NAME,DATEBIRTH,ADDRESS,TENANT,TENANTS,CATEGORY,TITLE,PRICE,YEAR,WEIGHT,COLOR,TYPE,LENGTH,
	SIZE,BIKE,SKATE,SKIES,GLASSES,GLOVES,GLOVESWINTER,HELMET,PROTECTION,SKIPOLES,PRODUCTS
}
